database:
  type: sqlite
  path: /app/vikunja/db/vikunja.db

files:
  basepath: /app/vikunja/files

service:
  enableregistration: false
  publicurl: https://vikunja.lhartung.com
  timezone: America/Chicago
